### PR TITLE
Release: 3.5.3

### PR DESCRIPTION
**Pull request by joshdholtz**
## 3.5.3                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                               
- Fixed a bug where [namespace Editor on iOS post install collided with UnityEditor.Editor](https://github.com/RevenueCat/purchases-unity/issues/98)                                                                                                           
    https://github.com/RevenueCat/purchases-unity/pull/99

### CODE REVIEW

**Review by aboedo — APPROVED** [review]
🚢

**Review by vegaro — APPROVED** [review]

**Comment by joshdholtz** [comment]
:shipit:

**Comment by vegaro** [comment]
@joshdholtz I am testing an automated solution to rename Dummy.swift to RevenueCatDummy.swift on install. If I don't get it to work today, I will just ship as is

**Comment by vegaro** [comment]
Alright I haven't managed the manifest file thing to remove the obsolete files, so I think we should just release this and be very clear in the changelog. If someone is having issues we can point to this release and explain they have to remove the old file.

**Pull request merged**
